#!/bin/sh

rpglelint="./rpglelint";
if test -n "$1"
then
	set -- t/"$1"*.rpgle
else
	set -- t/[0-9][0-9]-*.rpgle
fi

for file
do
	test -f "$file" || continue
	for format in unix json
	do
		expfile=${file%.*}.$format

		if test -f "$expfile"
		then
			# run test
			printf '$ %s\n' "$rpglelint -f$format $file | diff $expfile -"
			"$rpglelint" -f"$format" "$file" | diff "$expfile" - || exit 2
		else
			# create expected output
			printf '$ %s\n' "$rpglelint -f$format $file > $expfile"
			"$rpglelint" -f"$format" "$file" > "$expfile"
		fi
	done
done
